trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  persistCredentials: true
- task: oc-setup@3
  inputs:
    connectionType: 'OpenShift Connection Service'
    openshiftService: 'OpenShift cluster'
    version: '3.11.0'
- script: |
    oc project testlu
    cd $AGENT_TOOLSDIRECTORY
    ls
    cd oc 
    ls
    cd 3.11.0/x64
    ls
